### ISSUE TITLE
Doesn't work on Redmine 2.3.1

### ISSUE THREAD

**Issue by max-biodatomics** [behigh/redmine_timelog_timer#13]

**Comment by JongleurX** [comment]
We're having problems with 2.3.1 as well. Here is our setup.

| Item | Value |
| --- | --- |
| Redmine version | 2.3.1.devel |
| Ruby version | 1.8.7 (amd64-freebsd9) |
| Rails version | 3.2.13 |
| Database adapter | PostgreSQL |

I will follow up with details if I can get them from my sysadmin.

**Comment by bryangruneberg** [comment]
Same here :)

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.8.7 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         MySQL
Redmine plugins:
  timelog_timer                            2.0.0

**Comment by XERAEN** [comment]
Same on 2.3.2

| Item | Value |
| --- | --- |
| Redmine version | 2.3.2 stable |
| Ruby version | 1.9.3-p448 (x86_64-linux) |
| Rails version | 3.2.13 |
| DB adapter | mysql2 |

**Comment by qmclaugh** [comment]
yep, fail in 2.3.1

**Comment by Gappa** [comment]
Currently using it in 2.3.3.stable (skipped .1 and .2 though) and it is working.

**Comment by yecine06** [comment]
does not work for me on 2.3.3 (cloned repository from github)

```
Started GET "/settings?tab=authentication" for 127.0.0.1 at 2013-12-08 18:57:49 -0500
Processing by SettingsController#index as HTML
  Parameters: {"tab"=>"authentication"}
  Current user: ydhouib (id=3)
  Rendered settings/_general.html.erb (11.0ms)
  Rendered settings/_display.html.erb (11.0ms)
  Rendered settings/_authentication.html.erb (9.6ms)
  Rendered settings/_projects.html.erb (16.6ms)
  Rendered queries/_columns.html.erb (9.2ms)
  Rendered settings/_issues.html.erb (19.4ms)
  Rendered settings/_notifications.html.erb (10.2ms)
  Rendered settings/_mail_handler.html.erb (3.3ms)
  Rendered settings/_repositories.html.erb (22.7ms)
  Rendered common/_tabs.html.erb (117.2ms)
  Rendered settings/edit.html.erb within layouts/admin (118.4ms)
  Rendered admin/_menu.html.erb (8.8ms)
  Rendered layouts/base.html.erb (10.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.4ms)
Completed 500 Internal Server Error in 157ms

ActionView::Template::Error (Missing partial timelog/timer with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/home/redmine/source/plugins/redmine_update_reminder/app/views"
  * "/home/redmine/source/plugins/redmine_timesheet_plugin/app/views"
  * "/home/redmine/source/plugins/redmine_spent_time_required/app/views"
  * "/home/redmine/source/plugins/redmine_flowdock/app/views"
  * "/home/redmine/source/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: <!-- page specific tags -->
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb__3859349718176239020_26242940'
  app/controllers/application_controller.rb:420:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:418:in `render_error'
  app/controllers/application_controller.rb:406:in `render_404'
  app/controllers/application_controller.rb:430:in `missing_template'

```

**Comment by eskuai** [comment]
failed in  2.4.4.stable too !

**Comment by mikeploeger** [comment]
Doesn't work on 2.5.3 as well.
Error Log:

```
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.7ms)
  Rendered inline template (0.6ms)
  Rendered inline template (0.6ms)
Completed 500 Internal Server Error in 567.2ms

ActionView::Template::Error (Missing partial timelog/timer with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/redmine-2.5/plugins/redmine_work_time/app/views"
  * "/redmine-2.5/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: <!-- page specific tags -->
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb___627462558045010058_70007699388800'
  app/controllers/application_controller.rb:452:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:450:in `render_error'
  app/controllers/application_controller.rb:438:in `render_404'
  app/controllers/application_controller.rb:462:in `missing_template'
```

**Comment by mikeploeger** [comment]
New working version & actively maintained repository:
https://github.com/emovere/redmine_timelog_timer/
