### ISSUE TITLE
it seemed not support redmine2.1.4?

### ISSUE THREAD

**Issue by archonwang** [behigh/redmine_timelog_timer#8]
I test it on redmine 2.1.4 and found it does not work.
the error  is
# 

Started GET "/" for 192.168.3.196 at 2012-12-21 13:37:01 +0800
Processing by WelcomeController#index as HTML
  Current user: wangshuangying (id=190)
  Rendered news/_news.html.erb (8.4ms)
  Rendered welcome/index.html.erb within layouts/base (17.2ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.4ms)
  Rendered plugins/redmine_cut_tag/app/views/hooks/redmine_cut_tag/_includes.html.erb (0.7ms)
  Rendered plugins/redmine_improved_searchbox/app/views/redmine_improved_searchbox/_redmine_improved_searchbox_partial.html.erb (0.1ms)
  Rendered plugins/redmine_private_wiki/app/views/hooks/_html_header.html.erb (0.2ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.5ms)
  Rendered plugins/redmine_cut_tag/app/views/hooks/redmine_cut_tag/_includes.html.erb (0.7ms)
  Rendered plugins/redmine_improved_searchbox/app/views/redmine_improved_searchbox/_redmine_improved_searchbox_partial.html.erb (0.1ms)
  Rendered plugins/redmine_private_wiki/app/views/hooks/_html_header.html.erb (0.1ms)
Completed 500 Internal Server Error in 88ms

ActionView::Template::Error (Missing partial timelog/timer with {:locale=>[:zh, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
- "/opt/lampp/htdocs/redmine_2_1/plugins/unread_issues/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_xls_export/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_vividtone_my_page_blocks/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_testlinklink/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_spent_time/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_smart_issues_sort/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_reorder_links_arbitrary/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_refresh/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_projects_accordion/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_private_wiki/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_preview_attach_column/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_monitoring_controlling/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_logs/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_local_avatars/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_lightbox/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_knowledgebase/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_issue_checklist/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_inline_attach_screenshot/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_information/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_improved_searchbox/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_graphs/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_extra_query_operators/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_evm/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_didyoumean/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_cut_tag/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_csv_file_importer/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_close_button/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_ckeditor/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/redmine_changeauthor/app/views"
- "/opt/lampp/htdocs/redmine_2_1/plugins/advanced_roadmap/app/views"
- "/opt/lampp/htdocs/redmine_2_1/app/views"
  ):
  11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
  12: <%= javascript_heads %>
  13: <%= heads_for_theme %>
  14: <%= call_hook :view_layouts_base_html_head %>
  15: 
  16: <%= yield :header_tags -%>
  17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in`_1228a8285bc6050fcbbf7dd4a481fe8f'
  app/controllers/application_controller.rb:360:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:358:in`render_error'
  app/controllers/application_controller.rb:346:in `render_404'
  app/controllers/application_controller.rb:370:in`missing_template'

**Comment by cforce** [comment]
I have exactly the same prpoblem with redmine 2.1.4  !!

**Comment by behigh** [comment]
The plugin is installed in timelog_timer dir?

**Comment by behigh** [comment]
Tested on 2.1.4 and 2.2.0 and work fine for me.

**Comment by cforce** [comment]
> The plugin is installed in timelog_timer dir?
> Touche. RTFM ;(

**Comment by hishammalik** [comment]
had the same issue and all I had to do was to rename the plugin folder from redmine_timelog_timer to timelog_timer.

Actually, the correct thing would be to refactor the plugin name to be redmine_timelog_timer, but for now the above does the trick.

**Comment by mikeploeger** [comment]
This repository is no longer actively maintained.

New working version & actively maintained repository:
https://github.com/emovere/redmine_timelog_timer/
